<a href="https://colab.research.google.com/github/Huzaifa-Alam/Python-Data_Analysis/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# why we dont use python list instead of numpy array

# 1) list contain diiferent data types at once like[ 1 ,"huzaifa" ,True  , 1.1]
# where as numpy only contain one data type like[ "huzaifa" "ahmed" , "owais"] which make it more eficient
                                             # [1,2,3,4,5]

# WHY SHOULD WE USE NUMPY
# it's 300 times faster than pyhton list
# take less memory to store data




In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

# list VS numpy arrays

In [ ]:
python_list = [1 , "huzaifa" , True , 22.1]
python_list

[1, 'huzaifa', True, 22.1]

In [ ]:
numpy_list = np.array([1 , "huzaifa" , True , 22.1])
numpy_list # return same data type

array(['1', 'huzaifa', 'True', '22.1'], dtype='<U32')

In [ ]:
for element in python_list:
  print(type(element))


<class 'int'>
<class 'str'>
<class 'bool'>
<class 'float'>


In [ ]:
for element in numpy_list:
  print(type(element))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
# arryas contain rows data
# nasted list [[1,2],[3,4]]
arrs = np.array([[1,2],[3,4],[5,6]])
arrs

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arrs[-1]# last listt
arrs[-1][-1]# last listt

6

In [ ]:
# NDARRAY  "n-dimentional-array" an array with any number of dimension 1-D 2-D 3-D .........
# vector (single  dimnension 1-D)
# matrix (double dimension 2-D)
# tensor (3-D or any other dimensaional array)

In [ ]:
arrays = np.array([[1,2,32],[3,4,241],[5,6,124]])
arrays

array([[  1,   2,  32],
       [  3,   4, 241],
       [  5,   6, 124]])

In [ ]:
arrays.shape

(3, 3)

In [ ]:
arrays.dtype

dtype('int64')

In [ ]:
# arrays = np.array([[1,2,32],[3,4,241],[5,6,124]] , dtype="int")
arrays = np.array([[1,2,32],[3,4,241],[5,6,124]] , dtype="str")
arrays

array([['1', '2', '32'],
       ['3', '4', '241'],
       ['5', '6', '124']], dtype='<U3')

In [ ]:
arrays.dtype

dtype('<U3')

In [ ]:
empty = np.empty(5) # its more efficent
empty

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [ ]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [ ]:
# creating a range will use Arange means single range or ekrange
my_range = np.arange(9)
my_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# my_range = np.arange("start" , "end" , "step or jump")
# list multiple of 3 or which are factors of 3 till 30
my_range = np.arange(3 , 31 ,3)
my_range

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
#spaced (divide) linaerly in specified intervals will use linspace()

divide = np.linspace(0 , 50 , num =11) #num = how many parts do u want split in the given list
divide

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [ ]:
sort = np.sort([23,13,655,23,523543,657,3,544,423,12,5,236])
sort

array([     3,      5,     12,     13,     23,     23,    236,    423,
          544,    655,    657, 523543])

In [ ]:
# concatenate joins two or more arrays
first_arr = [23,13,655,23,12,5,236]
second_arr = [44,12,5,236]
concatenate = np.concatenate((first_arr , second_arr))   # SOULD BE IN TUPLE
concatenate

array([ 23,  13, 655,  23,  12,   5, 236,  44,  12,   5, 236])

In [ ]:
first_arr_multiindex = [[23,13], [23,12]] # all the input arrays must have same number of dimensions
second_arr_multiindex  = [[44,12],[5,236]]
join = np.concatenate((first_arr_multiindex,second_arr_multiindex))
join

array([[ 23,  13],
       [ 23,  12],
       [ 44,  12],
       [  5, 236]])

In [ ]:
first_arr_multiindex = [[23,13], [23,12]] # all the input arrays must have same number of dimensions
second_arr_multiindex  = [[44,12],[5,236]]
# join = np.concatenate((first_arr_multiindex,second_arr_multiindex) , axis = 0) #rows will be concatenate  means row is join
join = np.concatenate((first_arr_multiindex,second_arr_multiindex) , axis = 1) # column will be concatenate means column will be join
join

array([[ 23,  13,  44,  12],
       [ 23,  12,   5, 236]])

# shape and size of an array VID (109)

In [ ]:
three_dimensional_list = np.array([[[1, 2, 3], [4, 5, 6]],
                          [[10, 11, 12], [13, 14, 15]],
                          [[19, 20, 21], [22, 23, 24]]])
three_dimensional_list

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [ ]:
# number of dimension of any given array usin NDIM
three_dimensional_list.ndim

3

In [ ]:
list = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
list

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
list.ndim

3

In [ ]:
two_dimensional_list = np.array([[[1,3], [4, 6]],
                          [[10, 12], [13,  15]],
                          [[19, 21], [22, 24]]])
two_dimensional_list

array([[[ 1,  3],
        [ 4,  6]],

       [[10, 12],
        [13, 15]],

       [[19, 21],
        [22, 24]]])

In [ ]:
two_dimensional_list.ndim

3

In [ ]:
# .SIZE return total number of elements in list
three_dimensional_list.size

18

In [ ]:
three_dimensional_list.shape
#3 list that contain 2 list having 3 elements (3,2,3)

(3, 2, 3)

# reshaping an array(list)

In [ ]:
arr = np.array(['a','b','c','d','e','f'])
arr

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [ ]:
# arr
arr.reshape(3,2) # 3 list of 2 elements in each

array([['a', 'b'],
       ['c', 'd'],
       ['e', 'f']], dtype='<U1')

In [ ]:
arr

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [ ]:
arr.reshape(2,3) # 2 list of 3 elements
# reshapr shoulb be compataible to the list cant be like this
# arr.reshape(6,3)

array([['a', 'b', 'c'],
       ['d', 'e', 'f']], dtype='<U1')

In [ ]:
np.reshape(arr, newshape = (1,2,3)) # 1 list that contaon 2 list having 3 elements
np.reshape(arr, newshape = (1,2,3)) # 1 list of 2 list of 3 elements

array([[['a', 'b', 'c'],
        ['d', 'e', 'f']]], dtype='<U1')

# adding new axis(new axis and expand dimension)

In [ ]:
import numpy as np


In [ ]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr.shape
# 6 elements

(6,)

In [ ]:
# add new axis(row ) to the list OR ADDING ROW
arr2 = arr[np.newaxis  ,  : ]
arr2

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
arr2.shape

(1, 6)

In [ ]:
# ADDING COLUMN
arr3 = arr[ : , np.newaxis]
arr3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
arr3.shape
# 6 list of one element

(6, 1)

In [ ]:
# ANOTHER METHOS WE CAN USE INSTEAD OF NEWAXIS
# WE WIL USE .EXPAND_DIMS #  which means expand dimensions


In [ ]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
row = np.expand_dims(arr, axis = 0)#will add a new axis as a ROW  (axis 0 set as a  row)
row

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
col = np.expand_dims(arr ,  axis  =  1) # will addd anew column as  a column
col

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
col.shape

(6, 1)

# indexing and slicing

In [ ]:
import numpy as np
# list = np.arange(0,10 ,1)  #both are same
list = np.arange(10)
list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# will reverse the order of a list
list[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
# list["any condion here"]
list[list > 5]

array([6, 7, 8, 9])

In [ ]:

# even_num  =  list[list%2 == 0]
# even_num


In [ ]:
array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
mask = np.nonzero(array>5)
mask
# list-->[1, 1, 1] having indices [1, 2, 3] which satisfy the condtion
# list-->[2, 2, 2] having indices [0, 1, 2, 3] which satisfy the condtion

(array([1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3]))

In [ ]:
array[mask]

array([ 6,  7,  8,  9, 10, 11, 12])

# creating array(list) from existing list

In [ ]:
Genuine = np.arange(10)
Genuine


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
original_copy = Genuine.copy() # soo original list will ramain same
original_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
slicing  =  original_copy[2:8]
slicing

array([2, 3, 4, 5, 6, 7])

In [ ]:
slicing[0] = 60
slicing

array([60,  3,  4,  5,  6,  7])

In [ ]:
Genuine # will not change we use method original.copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
original_copy

array([ 0,  1, 60,  3,  4,  5,  6,  7,  8,  9])

# BASIC operation (maths)

In [ ]:
list1 = np.array([[1,4, 6] ,  [7,8,9]])
list2 = np.array([[11,14,16] , [17,18,19]])


In [ ]:
list1 + list2 # will add 1st element of tthe first list With 1st element of the sceond list
list2 - list1

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
list2 / list1
list2 * list1

array([[ 11,  56,  96],
       [119, 144, 171]])

In [ ]:
arr = np.array([[1,2,3],[7,8,9]])
arr

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
arr.sum()
arr.max()
arr.min()
arr.mean()

5.0

In [ ]:
# we can specify the axis
row_sum = arr.sum(axis = 0)
row_sum
# also
arr.sum(axis = 1)

array([ 6, 24])

# broadcasting

In [ ]:
# come with numpy
import numpy as ni
arr_ni = np.array([10,20,30])
arr_ni

array([10, 20, 30])

In [ ]:
arr_ni * .5
arr_ni / 2

array([ 5., 10., 15.])

# MATRICES

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
multiply = np.array([10,5,2])
arr * multiply

array([[10, 10,  6],
       [40, 25, 12],
       [70, 40, 18]])

In [ ]:
arr.mean(axis=0)

array([4., 5., 6.])

In [ ]:
# generate matrices with differrent random numbers
# it will return floart RANGE 0 to 1
RandomRange = np.random.default_rng()
RandomRange.random(5)


array([0.07238314, 0.59680478, 0.30608223, 0.36312704, 0.65753047])

In [ ]:
# also
RandomRange.random((4 , 2)) # list of four having 2 elements in each

array([[0.20660831, 0.51233849],
       [0.64866621, 0.43819027],
       [0.27060195, 0.30403   ],
       [0.4039876 , 0.65755671]])

In [ ]:
RandomRange

Generator(PCG64) at 0x781B11080820

In [ ]:
# generator # apply integer random numbers
RandomRange.integers(low = 1 , high = 50 , size = (4,3)) # 50 is not included here

array([[48, 47, 35],
       [26, 30, 18],
       [24, 13,  9],
       [28,  3,  6]])

In [ ]:
generator = np.random.default_rng()
generator.integers(low=50 ,high = 101 , size=(3,2))

array([[84, 77],
       [93, 62],
       [82, 90]])

In [ ]:
RandomRange.random(size=(3,3))# will return in float
# RandomRange.random(size=(3,3 ,4))# this is extremly user friendly

array([[0.99396129, 0.09366848, 0.72968486],
       [0.14920649, 0.74045697, 0.19553653],
       [0.78197608, 0.17260284, 0.5991006 ]])

In [ ]:
# print('hello i am wasting a lot of time guzra waqt kabhi wapis ata nhi')


# finding Unique Elements

In [ ]:
import numpy as np


In [ ]:
arr = np.array([1,4,2,3,5,2,1,4,6,1,1,2,3,1,5,4,6,6])

In [ ]:
np.unique(arr) # give un a unique forms means will ignore repeating value


array([1, 2, 3, 4, 5, 6])

In [ ]:
np.unique(arr , return_index=True)

(array([1, 2, 3, 4, 5, 6]), array([0, 2, 3, 1, 4, 8]))

In [ ]:
np.unique(arr , return_index=True , return_counts=True)


(array([1, 2, 3, 4, 5, 6]),
 array([0, 2, 3, 1, 4, 8]),
 array([5, 3, 2, 3, 2, 3]))

In [ ]:
list = np.array([[1,3,1] ,
                [3,3,3],
                [1,3,1]])
# list = np.array([[1,3,1] ,[3,3,3],[1,3,1]])
list

array([[1, 3, 1],
       [3, 3, 3],
       [1, 3, 1]])

In [ ]:
np.unique(list , axis = 0 )# will not return identical row

array([[1, 3, 1],
       [3, 3, 3]])

In [ ]:
np.unique(list , axis = 1)# will not return identical column

array([[1, 3],
       [3, 3],
       [1, 3]])

# transposing and Reshaping arrays

In [ ]:
arr  =  np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr.reshape(4,2) # 4 rows  2 columns

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
arr.reshape(1,8 )   # 1 row and 8 columns

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr.transpose() # change the axes of an array

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
arr.transpose().transpose() # will return the original array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Reverse an array

In [ ]:
import numpy as np
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr[::-1]

array([7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
# another method of reverse an array is
np.flip(arr)

array([7, 6, 5, 4, 3, 2, 1, 0])

WHAT ABOUT 2-D LIST (MATRICES)

In [ ]:
two_d = np.array([[1,2,3],[4,5,6],[7,8,9]])
two_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# if we do like this we will get slighty diiferent result
two_d[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
# we can speicify the axes
np.flip(two_d)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
np.flip(two_d , axis = 0)


array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
np.flip(two_d , axis = 1)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [ ]:
np.flip(two_d[2])

array([9, 8, 7])

In [ ]:
two_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.flip(two_d[: , 2]) # reverse a single column at the index two

array([9, 6, 3])

# reshaping and flattenting multidimensal arrays

In [ ]:
arr =  np.array([[1,2,3,11],[4,5,6,12],[7,8,9,13]])
arr

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 13]])

In [ ]:
# flattening means converting multidimensional into 1-D dimension
arr.flatten()
arr.ravel() # both are same there is minor mistake which we are going to look at it
# THE DIIFERENCE IS FALTTERN IS NOT AFFECT THE ORIGINAL ARRAY ON THE OTHER HAND RAVEL DO (change the original array) eaxmple

array([ 1,  2,  3, 11,  4,  5,  6, 12,  7,  8,  9, 13])

In [ ]:
flatten = arr.flatten()
flatten[0]= 10
flatten

array([10,  2,  3, 11,  4,  5,  6, 12,  7,  8,  9, 13])

In [ ]:
arr

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 13]])

In [ ]:
ravel = arr.ravel()
ravel[0] = 10
ravel

array([10,  2,  3, 11,  4,  5,  6, 12,  7,  8,  9, 13])

In [ ]:
arr

array([[10,  2,  3, 11],
       [ 4,  5,  6, 12],
       [ 7,  8,  9, 13]])

# saving and loading arrays

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

np.save("file name" , name of list) Extension should be .npy with the file name  & store single object(list)

np.savez("file name" , name of list) Extension should be .npz with the file name  & store multi objects(many list)

In [ ]:
np.save("my_new_array.npy" , arr) # saving it as a numpy binary file


In [ ]:
np.load("my_new_array.npy")

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

EFFICIENCE WAY TO STORE LIST IS IN THE BINARY FORMS


we can also save .txt an .csv files

np.savetxt(same format) no matter csv file or txt file we always use save.txt

In [ ]:
np.savetxt("my_text_file.txt" , arr )
# np.savetxt("my_text_file.csv" , arr)

In [ ]:
np.loadtxt("my_text_file.txt")# both will give same result

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])